name: cardioscope_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Loosened the SDK constraint for better compatibility

dependencies:
  flutter:
    sdk: flutter
  
  # Core Functionality
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  intl: ^0.19.0 # Updated to a more recent version
  
  # UI & Charts
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0

  # Hardware & Permissions
  flutter_blue_plus: ^1.5.0
  permission_handler: ^11.3.0
  audioplayers: ^5.2.1

  # AI & Reporting
  tflite_flutter: ^0.10.4
  pdf: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to a more recent version

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/