import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';

import '../database_helper.dart';

class PdfExporter {
  static final _screenshotController = ScreenshotController();

  // Global date formatter for consistency
  static final _dateTimeFormat = DateFormat('MMMM d, yyyy – hh:mm a');
  static final _dateOnlyFormat = DateFormat('MMMM d, yyyy');

  // --------------------------------------------------------------------------
  // SINGLE REPORT
  // --------------------------------------------------------------------------
  static Future<void> exportSingleReport({
    required Map<String, dynamic> report,
    required String practitionerName,
  }) async {
    final pdf = pw.Document();
    final logo = pw.MemoryImage(
        (await rootBundle.load('assets/images/app_logo.png')).buffer.asUint8List());
    final now = _dateTimeFormat.format(DateTime.now());
    final waveformImage = await _generateWaveformImage(report['file_path']);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (context) => _buildHeader(practitionerName, now, logo),
        footer: (context) => _buildFooter(context, practitionerName),
        build: (context) => [
          _buildReportContent(report, waveformImage),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File("${dir.path}/CardioScope_Report_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)], text: "CardioScope Report");
  }

  // --------------------------------------------------------------------------
  // BATCH REPORTS
  // --------------------------------------------------------------------------
  static Future<void> exportBatchReports({
    required List<Map<String, dynamic>> reports,
    required String practitionerName,
    required DateTimeRange dateRange,
  }) async {
    final pdf = pw.Document();
    final logo = pw.MemoryImage(
        (await rootBundle.load('assets/images/app_logo.png')).buffer.asUint8List());
    final now = _dateTimeFormat.format(DateTime.now());

    for (final report in reports) {
      final waveformImage = await _generateWaveformImage(report['file_path']);
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          header: (context) => _buildHeader(practitionerName, now, logo),
          footer: (context) => _buildFooter(context, practitionerName),
          build: (context) => [
            _buildReportContent(report, waveformImage),
          ],
        ),
      );
    }

    final dir = await getTemporaryDirectory();
    final startDate = DateFormat('yyyy-MM-dd').format(dateRange.start);
    final endDate = DateFormat('yyyy-MM-dd').format(dateRange.end);
    final filename =
        "CardioScope_Batch_${practitionerName.replaceAll(' ', '_')}_${startDate}_to_$endDate.pdf";
    final file = File("${dir.path}/$filename");
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)], text: "CardioScope Batch Reports");
  }

  // --------------------------------------------------------------------------
  // HEADER
  // --------------------------------------------------------------------------
  static pw.Widget _buildHeader(
      String practitionerName, String now, pw.MemoryImage logo) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text("CardioScope Report",
                style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: const PdfColor.fromInt(0xFF2c3e50))),
            pw.SizedBox(height: 8),
            pw.Text("Generated by: $practitionerName",
                style: const pw.TextStyle(color: PdfColors.grey700)),
            pw.Text("Date Generated: $now",
                style: const pw.TextStyle(color: PdfColors.grey700)),
          ],
        ),
        pw.SizedBox(height: 50, width: 50, child: pw.Image(logo)),
      ],
    );
  }

  // --------------------------------------------------------------------------
  // REPORT CONTENT
  // --------------------------------------------------------------------------
  static pw.Widget _buildReportContent(
      Map<String, dynamic> report, pw.ImageProvider? waveformImage) {
    Map<String, dynamic> probs = {};
    if (report['probabilities'] is String &&
        (report['probabilities'] as String).isNotEmpty) {
      try {
        probs = jsonDecode(report['probabilities']);
      } catch (_) {}
    } else if (report['probabilities'] is Map<String, dynamic>) {
      probs = report['probabilities'];
    }

    final patientId = report['patient_id'] != null
        ? DatabaseHelper.instance.formatPatientId(report['patient_id'])
        : 'N/A';

    String recordDateStr = 'N/A';
    if (report['record_date'] != null) {
      try {
        recordDateStr = _dateTimeFormat.format(DateTime.parse(report['record_date']));
      } catch (_) {}
    }

    String birthdayStr = 'N/A';
    if (report['birthday'] != null && report['birthday'].toString().isNotEmpty) {
      try {
        birthdayStr = _dateOnlyFormat.format(DateTime.parse(report['birthday']));
      } catch (_) {
        birthdayStr = report['birthday'].toString();
      }
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(height: 20),
        _buildSectionHeader("Patient Details"),
        _buildDetailRow("Patient ID:", patientId),
        _buildDetailRow("Name:", report['name'] ?? 'N/A'),
        _buildDetailRow("Birthday:", birthdayStr),
        _buildDetailRow("Age:", report['age']?.toString() ?? 'N/A'),
        _buildDetailRow("Gender:", report['gender'] ?? 'N/A'),
        pw.SizedBox(height: 20),
        _buildSectionHeader("Recording Details"),
        _buildDetailRow("Record Date:", recordDateStr),
        pw.SizedBox(height: 20),
        _buildSectionHeader("Phonocardiogram (PCG)"),
        pw.Container(
          height: 100,
          width: double.infinity,
          margin: const pw.EdgeInsets.only(top: 8),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: waveformImage != null
              ? pw.Image(waveformImage, fit: pw.BoxFit.fill)
              : pw.Center(
                  child: pw.Text("Waveform data not available.",
                      style: const pw.TextStyle(color: PdfColors.grey))),
        ),
        pw.SizedBox(height: 20),
        _buildSectionHeader("AI Analysis"),
        _buildDetailRow("Classification:", report['diagnosis'] ?? 'N/A'),
        if (probs.isNotEmpty) ...[
          pw.SizedBox(height: 12),
          pw.Text("Detailed Breakdown:",
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 5),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: probs.entries.map((e) {
              final percentage = ((e.value as num?)?.toDouble() ?? 0.0) * 100;
              return pw.Text("  •  ${e.key}: ${percentage.toStringAsFixed(2)}%");
            }).toList(),
          ),
        ],
      ],
    );
  }

  // --------------------------------------------------------------------------
  // SECTION / DETAIL HELPERS
  // --------------------------------------------------------------------------
  static pw.Widget _buildSectionHeader(String title) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title,
            style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: const PdfColor.fromInt(0xFF34495e))),
        pw.Divider(height: 8, color: PdfColors.black, thickness: 0.5),
        pw.SizedBox(height: 8),
      ],
    );
  }

  static pw.Widget _buildDetailRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(label,
                style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold, color: PdfColors.grey800)),
          ),
          pw.Expanded(child: pw.Text(value)),
        ],
      ),
    );
  }

  // --------------------------------------------------------------------------
  // FOOTER (now includes practitioner line)
  // --------------------------------------------------------------------------
  static pw.Widget _buildFooter(pw.Context context, String practitionerName) {
    return pw.Column(
      mainAxisSize: pw.MainAxisSize.min,
      children: [
        pw.Divider(color: PdfColors.grey400, height: 20),
        pw.Text(
          "*This AI analysis is a preliminary screening tool and is not a substitute for a professional medical diagnosis.*",
          style: pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
              fontStyle: pw.FontStyle.italic),
        ),
        pw.Text(
          "Page ${context.pageNumber} of ${context.pagesCount}",
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
      ],
    );
  }

  // --------------------------------------------------------------------------
  // WAVEFORM GENERATION
  // --------------------------------------------------------------------------
  static Future<pw.ImageProvider?> _generateWaveformImage(String? path) async {
    if (path == null) return null;
    final spots = await _loadWaveformData(path);
    if (spots.isEmpty) return null;

    final Uint8List imageBytes = await _screenshotController.captureFromWidget(
      _buildWaveformChart(spots),
      pixelRatio: 2.0,
    );

    return pw.MemoryImage(imageBytes);
  }

  static Widget _buildWaveformChart(List<FlSpot> spots) {
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.only(top: 10, bottom: 5, right: 10),
      child: LineChart(
        LineChartData(
          titlesData: const FlTitlesData(show: false),
          gridData: const FlGridData(show: false),
          borderData: FlBorderData(show: false),
          minY: -1,
          maxY: 1,
          lineBarsData: [
            LineChartBarData(
              spots: spots,
              isCurved: false,
              color: const Color(0xFF3498db),
              barWidth: 1.2,
              dotData: const FlDotData(show: false),
            ),
          ],
          lineTouchData: const LineTouchData(enabled: false),
        ),
      ),
    );
  }

  static Future<List<FlSpot>> _loadWaveformData(String path) async {
    final file = File(path);
    if (!await file.exists()) return [];
    final bytes = await file.readAsBytes();
    if (bytes.lengthInBytes <= 44) return [];

    final pcmBytes = bytes.sublist(44);
    final byteData = ByteData.view(pcmBytes.buffer);
    final spots = <FlSpot>[];
    const downsample = 50;
    for (int i = 0; i < pcmBytes.lengthInBytes; i += (2 * downsample)) {
      if (i + 2 <= pcmBytes.lengthInBytes) {
        final sample = byteData.getInt16(i, Endian.little) / 32768.0;
        spots.add(FlSpot((i / 2).toDouble(), sample));
      }
    }
    return spots;
  }
}
